"""Parameterised TRex profile templates for DoS-like workloads.

Each builder returns a Python source string that, when executed by the
TRex daemon via STLProfile.load_py / ASTFProfile.load_py, registers a
profile with the right streams or flow definitions. The returned text is
valid Python — callers may validate with ``compile(source, '<profile>',
'exec')``."""

import textwrap


def build_syn_flood_profile(
    *,
    src_cidr: str,
    dst_ips: tuple[str, ...],
    dst_ports: tuple[int, ...],
    rate_pps: int,
) -> str:
    """STL profile. Random src-IP within src_cidr, random dst-port from
    dst_ports, TCP SYN only, rate_pps packets per second aggregate."""
    return textwrap.dedent(f"""\
        # Auto-generated by shorewall_nft_stagelab.trafgen_trex_profiles
        from trex_stl_lib.api import (
            STLProfile, STLStream, STLTXCont, STLPktBuilder,
            STLVmFlowVar, STLVmFixIpv4, STLVmWrFlowVar,
        )
        from scapy.all import Ether, IP, TCP


        class SynFloodProfile:
            def __init__(self):
                self.src_cidr = {src_cidr!r}
                self.dst_ips = {list(dst_ips)!r}
                self.dst_ports = {list(dst_ports)!r}
                self.rate_pps = {rate_pps}

            def _pkt(self):
                base = Ether()/IP(src="0.0.0.0", dst=self.dst_ips[0])/TCP(
                    flags="S", dport=self.dst_ports[0], sport=1024,
                )
                vm = [
                    STLVmFlowVar("src_ip", min_value=self.src_cidr.split("/")[0],
                                 max_value=self.src_cidr.split("/")[0], size=4, op="random"),
                    STLVmWrFlowVar(fv_name="src_ip", pkt_offset="IP.src"),
                    STLVmFixIpv4(offset="IP"),
                ]
                return STLPktBuilder(pkt=base, vm=vm)

            def get_streams(self, direction=0, **kw):
                return [STLStream(
                    packet=self._pkt(),
                    mode=STLTXCont(pps=self.rate_pps),
                )]


        def register():
            return SynFloodProfile()
    """)


def build_udp_flood_profile(
    *,
    src_cidr: str,
    dst_ips: tuple[str, ...],
    dst_ports: tuple[int, ...],
    payload_size_b: int,
    rate_pps: int,
) -> str:
    """STL profile. UDP payload filled with 0x00 bytes of given size."""
    return textwrap.dedent(f"""\
        # Auto-generated by shorewall_nft_stagelab.trafgen_trex_profiles
        from trex_stl_lib.api import (
            STLProfile, STLStream, STLTXCont, STLPktBuilder,
            STLVmFlowVar, STLVmFixIpv4, STLVmWrFlowVar,
        )
        from scapy.all import Ether, IP, UDP, Raw


        class UdpFloodProfile:
            def __init__(self):
                self.src_cidr = {src_cidr!r}
                self.dst_ips = {list(dst_ips)!r}
                self.dst_ports = {list(dst_ports)!r}
                self.payload_size_b = {payload_size_b}
                self.rate_pps = {rate_pps}

            def _pkt(self):
                payload = Raw(load=b"\\x00" * self.payload_size_b)
                base = Ether()/IP(src="0.0.0.0", dst=self.dst_ips[0])/UDP(
                    dport=self.dst_ports[0], sport=1024,
                )/payload
                vm = [
                    STLVmFlowVar("src_ip", min_value=self.src_cidr.split("/")[0],
                                 max_value=self.src_cidr.split("/")[0], size=4, op="random"),
                    STLVmWrFlowVar(fv_name="src_ip", pkt_offset="IP.src"),
                    STLVmFixIpv4(offset="IP"),
                ]
                return STLPktBuilder(pkt=base, vm=vm)

            def get_streams(self, direction=0, **kw):
                return [STLStream(
                    packet=self._pkt(),
                    mode=STLTXCont(pps=self.rate_pps),
                )]


        def register():
            return UdpFloodProfile()
    """)


def build_dns_query_profile(
    *,
    src_cidr: str,
    resolver_ip: str,
    qnames: tuple[str, ...],
    qps: int,
    qtype: str = "A",
) -> str:
    """STL profile. UDP-53 queries with DNS question section (RFC 1035
    wire-format) using scapy's DNS/DNSQR classes inside the profile so
    the TRex daemon assembles the payload (NOT at build-time).

    qtype: DNS query type string forwarded to DNSQR (e.g. "A", "AAAA",
    "ANY", "TXT", "MX"). Default "A". Use "ANY" for amplification
    scenarios.
    """
    return textwrap.dedent(f"""\
        # Auto-generated by shorewall_nft_stagelab.trafgen_trex_profiles
        import random
        from trex_stl_lib.api import (
            STLProfile, STLStream, STLTXCont, STLPktBuilder,
            STLVmFlowVar, STLVmFixIpv4, STLVmWrFlowVar,
        )
        from scapy.all import Ether, IP, UDP
        from scapy.layers.dns import DNS, DNSQR


        class DnsQueryProfile:
            def __init__(self):
                self.src_cidr = {src_cidr!r}
                self.resolver_ip = {resolver_ip!r}
                self.qnames = {list(qnames)!r}
                self.qps = {qps}
                self.qtype = {qtype!r}

            def _pkt(self):
                qname = self.qnames[0]
                dns_payload = DNS(rd=1, qd=DNSQR(qname=qname, qtype=self.qtype))
                base = Ether()/IP(src="0.0.0.0", dst=self.resolver_ip)/UDP(
                    dport=53, sport=random.randint(1024, 65535),
                )/dns_payload
                vm = [
                    STLVmFlowVar("src_ip", min_value=self.src_cidr.split("/")[0],
                                 max_value=self.src_cidr.split("/")[0], size=4, op="random"),
                    STLVmWrFlowVar(fv_name="src_ip", pkt_offset="IP.src"),
                    STLVmFixIpv4(offset="IP"),
                ]
                return STLPktBuilder(pkt=base, vm=vm)

            def get_streams(self, direction=0, **kw):
                return [STLStream(
                    packet=self._pkt(),
                    mode=STLTXCont(pps=self.qps),
                )]


        def register():
            return DnsQueryProfile()
    """)


def build_half_open_profile(
    *,
    src_cidr: str,
    dst_ip: str,
    dst_port: int,
    target_conns: int,
    open_rate_per_s: int,
) -> str:
    """ASTF profile. Opens TCP connections to (dst_ip, dst_port) at the
    given rate, then idles indefinitely (no FIN, no payload). Aims to
    saturate target_conns concurrent half-open connections."""
    return textwrap.dedent(f"""\
        from trex.astf.api import (
            ASTFProfile, ASTFIPGenDist, ASTFIPGen, ASTFProgram,
            ASTFTCPInfo, ASTFCapInfo, ASTFCapEndp,
        )


        class HalfOpenProfile:
            def __init__(self):
                self.src_cidr = {src_cidr!r}
                self.dst_ip = {dst_ip!r}
                self.dst_port = {dst_port}
                self.target_conns = {target_conns}
                self.open_rate = {open_rate_per_s}

            def get_profile(self, tunables=None, **kw):
                # Client program: connect, then idle forever.
                prog_c = ASTFProgram()
                prog_c.connect()
                prog_c.delay(10**9)  # ~1000 s idle per conn

                # Server program: accept only (no reply), idle.
                prog_s = ASTFProgram()
                prog_s.accept()
                prog_s.delay(10**9)

                ip_gen = ASTFIPGen(
                    dist_client=ASTFIPGenDist(ip_range=[self.src_cidr.split('/')[0], self.src_cidr.split('/')[0]]),
                    dist_server=ASTFIPGenDist(ip_range=[self.dst_ip, self.dst_ip]),
                )

                tcp = ASTFTCPInfo(window=32768)
                cap = ASTFCapInfo(
                    ip_gen=ip_gen,
                    tcp=tcp,
                    c_glob_info=None, s_glob_info=None,
                    limit=self.target_conns,
                    cps=self.open_rate,
                    port=self.dst_port,
                    prog_c=prog_c, prog_s=prog_s,
                )
                return ASTFProfile(default_ip_gen=ip_gen, cap_list=[cap])


        def register():
            return HalfOpenProfile()
    """)
